<?php

/**
 * @file
 * Module file for Bene Features Example.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;

/**
 * Implements hook_help().
 */
function bene_salsa_help($route_name, RouteMatchInterface $route_match) {
  $page = NULL;
  switch ($route_name) {
    // This route is from the help module: just use the right machine name.
    case 'help.page.bene_salsa':
      $page = [
        'details' => [
          '#markup' => '<p>' . t('Example help page for Bene Features Example.') . '</p>',
        ],
        'video' => [
          '#type' => 'markup',
          '#markup' => '<div><iframe width="441" height="331" src="https://www.youtube.com/embed/Otbml6WIQPo" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>',
          '#allowed_tags' => [
            'iframe',
          ],
        ],
      ];
      break;

  }
  return $page;
}

/**
 * Implements hook_entity_view().
 */

function bene_salsa_hook_entity_view(array &$build, $entity, $display, $view_mode) {
    $form_code = '';
    $salsa_code = '';
    $build['salsa_embedded_form'] = [
        '#type' => 'inline_template',
        '#template' => '{{ embed|raw }}',
        '#context' => [
            'embed' => "<div id='hello'><script type='text/javascript' src='https://default.salsalabs.org/api/widgettemplate/hi/?tId=hello' ></script> \</div>",
        ],
    ];
}